"""empty message

Revision ID: 510bf364ef33
Revises: 577863a8bb03
Create Date: 2018-03-27 09:31:09.700472

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '510bf364ef33'
down_revision = '577863a8bb03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_provider', sa.Boolean(), nullable=True))
    op.drop_column('users', 'is_providers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_providers', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('users', 'is_provider')
    # ### end Alembic commands ###
