"""empty message

Revision ID: 577863a8bb03
Revises: fc1ec00271fd
Create Date: 2018-03-27 09:10:36.703137

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '577863a8bb03'
down_revision = 'fc1ec00271fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_providers', sa.Boolean(), nullable=True))
    op.drop_column('users', 'is_provider')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_provider', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('users', 'is_providers')
    # ### end Alembic commands ###
