"""empty message

Revision ID: fc1ec00271fd
Revises: 03e128ad17b6
Create Date: 2018-03-26 14:57:34.369161

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc1ec00271fd'
down_revision = '03e128ad17b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_provider', sa.Boolean(), nullable=True))
    op.drop_column('users', 'is_providers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_providers', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('users', 'is_provider')
    # ### end Alembic commands ###
